DEFINE VIEW {{db}}.STG.V_BUDGET_ITEMS(
    BUDGET_ID,
    FISCAL_YEAR,
    FISCAL_QUARTER,
    COST_CENTER_ID,
    ACCOUNT_ID,
    BUDGET_AMOUNT,
    ACTUAL_AMOUNT,
    CURRENCY_CODE,
    BUDGET_VERSION,
    APPROVED_BY,
    APPROVED_DATE
) as
select
    BUDGET_ID,
    FISCAL_YEAR,
    FISCAL_QUARTER,
    COST_CENTER_ID,
    ACCOUNT_ID,
    BUDGET_AMOUNT,
    ACTUAL_AMOUNT,
    CURRENCY_CODE,
    BUDGET_VERSION,
    APPROVED_BY,
    APPROVED_DATE
from {{db}}.RAW.BUDGET_ITEMS_RAW
qualify row_number() over (partition by BUDGET_ID order by LOAD_TS desc, RAW_SK desc) = 1;
