DEFINE VIEW {{db}}.RPT.VW_BUDGET_VARIANCE_BY_DIVISION(
    DIVISION,
    FISCAL_YEAR,
    FISCAL_QUARTER,
    TOTAL_BUDGET,
    TOTAL_ACTUAL,
    TOTAL_VARIANCE,
    VARIANCE_PCT
) as
select
    DIVISION,
    FISCAL_YEAR,
    FISCAL_QUARTER,
    sum(BUDGET_AMOUNT) as TOTAL_BUDGET,
    sum(ACTUAL_AMOUNT) as TOTAL_ACTUAL,
    sum(VARIANCE_AMOUNT) as TOTAL_VARIANCE,
    case when sum(BUDGET_AMOUNT) <> 0
        then round(sum(VARIANCE_AMOUNT) / sum(BUDGET_AMOUNT) * 100, 2)
        else null
    end as VARIANCE_PCT
from {{db}}.DM.F_BUDGET_VARIANCE
group by DIVISION, FISCAL_YEAR, FISCAL_QUARTER
order by FISCAL_YEAR desc, FISCAL_QUARTER desc, DIVISION;
