DEFINE VIEW {{db}}.RPT.VW_BUDGET_VARIANCE_BY_DIVISION(
    DIVISION,
    FISCAL_YEAR,
    FISCAL_QUARTER,
    TOTAL_BUDGET,
    TOTAL_ACTUAL,
    TOTAL_VARIANCE,
    VARIANCE_PCT
) AS
SELECT
    DIVISION,
    FISCAL_YEAR,
    FISCAL_QUARTER,
    SUM(BUDGET_AMOUNT) AS TOTAL_BUDGET,
    SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL,
    SUM(VARIANCE_AMOUNT) AS TOTAL_VARIANCE,
    CASE WHEN SUM(BUDGET_AMOUNT) <> 0
        THEN ROUND(SUM(VARIANCE_AMOUNT) / SUM(BUDGET_AMOUNT) * 100, 2)
        ELSE NULL
    END AS VARIANCE_PCT
FROM {{db}}.DM.F_BUDGET_VARIANCE
GROUP BY DIVISION, FISCAL_YEAR, FISCAL_QUARTER
ORDER BY FISCAL_YEAR DESC, FISCAL_QUARTER DESC, DIVISION;
