DEFINE VIEW {{db}}.RPT.VW_CURRENCY_RATES_SUMMARY(
    RATE_DATE,
    CURRENCY_PAIR,
    RATE,
    SOURCE_SYSTEM
) as
select
    RATE_DATE,
    FROM_CURRENCY || '/' || TO_CURRENCY as CURRENCY_PAIR,
    RATE,
    SOURCE_SYSTEM
from {{db}}.INT.V_CURRENCY_RATES_WITH_INVERSE
order by RATE_DATE desc, CURRENCY_PAIR;
