DEFINE VIEW {{db}}.RPT.VW_COUNTRY_DIRECTORY(
    COUNTRY_NAME,
    ISO2,
    CONTINENT,
    REGION,
    CURRENCY
) as
select
    COUNTRY_NAME,
    COUNTRY_CODE_ISO2 as ISO2,
    CONTINENT,
    REGION,
    CURRENCY_CODE || ' (' || CURRENCY_NAME || ')' as CURRENCY
from {{db}}.DM.D_COUNTRY
order by CONTINENT, COUNTRY_NAME;
