DEFINE VIEW {{db}}.STG.V_COMPENSATION_EVENTS(
    EMPLOYEE_ID,
    EFFECTIVE_DATE,
    SALARY_AMOUNT,
    BONUS_TARGET_PCT,
    CURRENCY_CODE,
    CHANGE_REASON,
    SRC_UPDATED_AT,
    LOAD_TS
) as
select
    EMPLOYEE_ID,
    EFFECTIVE_DATE,
    SALARY_AMOUNT,
    BONUS_TARGET_PCT,
    upper(CURRENCY_CODE) as CURRENCY_CODE,
    upper(CHANGE_REASON) as CHANGE_REASON,
    SRC_UPDATED_AT,
    LOAD_TS
from {{db}}.RAW.COMPENSATION_EVENTS_RAW
qualify row_number() over (
    partition by EMPLOYEE_ID, EFFECTIVE_DATE
    order by SRC_UPDATED_AT desc, LOAD_TS desc, RAW_ROW_ID desc
) = 1;
