DEFINE VIEW {{db}}.STG.V_DEPARTMENTS_CURRENT(
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    COST_CENTER,
    BUSINESS_UNIT,
    MANAGER_EMPLOYEE_ID,
    ACTIVE_FLAG,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT,
    SRC_UPDATED_AT,
    LOAD_TS
) as
select * from {{db}}.STG.V_DEPARTMENTS_HISTORY
where IS_CURRENT = true;
