DEFINE VIEW {{db}}.STG.V_EMPLOYEES_BASE(
    RAW_ROW_ID,
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    ETHNICITY,
    DATE_OF_BIRTH,
    HIRE_DATE,
    TERMINATION_DATE,
    EMPLOYMENT_STATUS,
    EMPLOYMENT_TYPE,
    EMAIL,
    IS_ACTIVE,
    SRC_UPDATED_AT,
    LOAD_TS,
    CHANGE_TS,
    ATTR_HASH
) as
select
    RAW_ROW_ID,
    EMPLOYEE_ID,
    initcap(FIRST_NAME) as FIRST_NAME,
    initcap(LAST_NAME) as LAST_NAME,
    upper(GENDER) as GENDER,
    ETHNICITY,
    DATE_OF_BIRTH,
    HIRE_DATE,
    TERMINATION_DATE,
    upper(EMPLOYMENT_STATUS) as EMPLOYMENT_STATUS,
    upper(EMPLOYMENT_TYPE) as EMPLOYMENT_TYPE,
    lower(EMAIL) as EMAIL,
    iff(upper(EMPLOYMENT_STATUS) = 'ACTIVE' and TERMINATION_DATE is null, true, false) as IS_ACTIVE,
    SRC_UPDATED_AT,
    LOAD_TS,
    coalesce(SRC_UPDATED_AT, LOAD_TS) as CHANGE_TS,
    md5(concat_ws('|',
        coalesce(initcap(FIRST_NAME), ''),
        coalesce(initcap(LAST_NAME), ''),
        coalesce(upper(GENDER), ''),
        coalesce(ETHNICITY, ''),
        coalesce(to_varchar(DATE_OF_BIRTH), ''),
        coalesce(to_varchar(HIRE_DATE), ''),
        coalesce(to_varchar(TERMINATION_DATE), ''),
        coalesce(upper(EMPLOYMENT_STATUS), ''),
        coalesce(upper(EMPLOYMENT_TYPE), ''),
        coalesce(lower(EMAIL), '')
    )) as ATTR_HASH
from {{db}}.RAW.EMPLOYEES_RAW;
