DEFINE VIEW {{db}}.STG.V_EMPLOYEES_CURRENT(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    ETHNICITY,
    DATE_OF_BIRTH,
    HIRE_DATE,
    TERMINATION_DATE,
    EMPLOYMENT_STATUS,
    EMPLOYMENT_TYPE,
    EMAIL,
    IS_ACTIVE,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT,
    SRC_UPDATED_AT,
    LOAD_TS
) as
select * from {{db}}.STG.V_EMPLOYEES_HISTORY
where IS_CURRENT = true;
