DEFINE VIEW {{db}}.RPT.VW_COMPENSATION_CURRENT(
    DEPARTMENT_NAME,
    JOB_FAMILY,
    EMPLOYEE_COUNT,
    AVG_SALARY,
    MIN_SALARY,
    MAX_SALARY
) as
select
    CURRENT_DEPARTMENT_NAME as DEPARTMENT_NAME,
    CURRENT_JOB_FAMILY as JOB_FAMILY,
    count(*) as EMPLOYEE_COUNT,
    avg(CURRENT_SALARY_AMOUNT) as AVG_SALARY,
    min(CURRENT_SALARY_AMOUNT) as MIN_SALARY,
    max(CURRENT_SALARY_AMOUNT) as MAX_SALARY
from {{db}}.DM.D_EMPLOYEE_CURRENT
where IS_ACTIVE = true
group by
    CURRENT_DEPARTMENT_NAME,
    CURRENT_JOB_FAMILY
order by
    CURRENT_DEPARTMENT_NAME,
    CURRENT_JOB_FAMILY;
