DEFINE VIEW {{db}}.RPT.VW_EMPLOYEE_CURRENT(
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    DEPARTMENT_NAME,
    JOB_TITLE,
    MANAGER_NAME,
    LOCATION_CODE,
    EMPLOYMENT_TYPE,
    SALARY_AMOUNT,
    BONUS_TARGET_PCT,
    CURRENCY_CODE,
    CURRENT_JOB_START_DATE,
    CURRENT_SALARY_EFFECTIVE_DATE
) as
select
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    CURRENT_DEPARTMENT_NAME as DEPARTMENT_NAME,
    CURRENT_JOB_TITLE as JOB_TITLE,
    CURRENT_MANAGER_NAME as MANAGER_NAME,
    CURRENT_LOCATION_CODE as LOCATION_CODE,
    EMPLOYMENT_TYPE,
    CURRENT_SALARY_AMOUNT as SALARY_AMOUNT,
    CURRENT_BONUS_TARGET_PCT as BONUS_TARGET_PCT,
    CURRENT_CURRENCY_CODE as CURRENCY_CODE,
    CURRENT_JOB_START_DATE,
    CURRENT_SALARY_EFFECTIVE_DATE
from {{db}}.DM.D_EMPLOYEE_CURRENT
where IS_ACTIVE = true;
