DEFINE VIEW {{db}}.RPT.VW_HEADCOUNT_BY_DEPARTMENT(
    DEPARTMENT_NAME,
    ACTIVE_HEADCOUNT
) as
select
    CURRENT_DEPARTMENT_NAME as DEPARTMENT_NAME,
    count(*) as ACTIVE_HEADCOUNT
from {{db}}.DM.D_EMPLOYEE_CURRENT
where IS_ACTIVE = true
group by CURRENT_DEPARTMENT_NAME
order by CURRENT_DEPARTMENT_NAME;
