DEFINE VIEW {{db}}.RPT.VW_MANAGER_SPAN_OF_CONTROL(
    MANAGER_NAME,
    DIRECT_REPORT_COUNT
) as
select
    coalesce(CURRENT_MANAGER_NAME, 'UNASSIGNED') as MANAGER_NAME,
    count(*) as DIRECT_REPORT_COUNT
from {{db}}.DM.D_EMPLOYEE_CURRENT
where IS_ACTIVE = true
group by coalesce(CURRENT_MANAGER_NAME, 'UNASSIGNED')
order by MANAGER_NAME;
