DEFINE VIEW {{db}}.RPT.VW_TENURE_BY_DEPARTMENT(
    DEPARTMENT_NAME,
    AVG_TENURE_DAYS,
    EMPLOYEE_COUNT
) as
select
    CURRENT_DEPARTMENT_NAME as DEPARTMENT_NAME,
    avg(datediff('day', HIRE_DATE, current_date())) as AVG_TENURE_DAYS,
    count(*) as EMPLOYEE_COUNT
from {{db}}.DM.D_EMPLOYEE_CURRENT
where IS_ACTIVE = true
group by CURRENT_DEPARTMENT_NAME
order by CURRENT_DEPARTMENT_NAME;
