DEFINE VIEW {{db}}.INT.V_EMPLOYEE_CURRENT_SNAPSHOT(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMPLOYEE_NAME,
    GENDER,
    ETHNICITY,
    DATE_OF_BIRTH,
    HIRE_DATE,
    TERMINATION_DATE,
    EMPLOYMENT_STATUS,
    EMPLOYMENT_TYPE,
    IS_ACTIVE,
    EMAIL,
    CURRENT_JOB_ID,
    CURRENT_JOB_TITLE,
    CURRENT_JOB_FAMILY,
    CURRENT_JOB_LEVEL,
    CURRENT_GRADE_BAND,
    CURRENT_DEPARTMENT_ID,
    CURRENT_DEPARTMENT_NAME,
    CURRENT_BUSINESS_UNIT,
    CURRENT_COST_CENTER,
    CURRENT_MANAGER_EMPLOYEE_ID,
    CURRENT_MANAGER_NAME,
    CURRENT_LOCATION_CODE,
    CURRENT_JOB_START_DATE,
    CURRENT_SALARY_AMOUNT,
    CURRENT_BONUS_TARGET_PCT,
    CURRENT_CURRENCY_CODE,
    CURRENT_SALARY_CHANGE_REASON,
    CURRENT_SALARY_EFFECTIVE_DATE
) as
with CURRENT_EMP as (
    select *
    from {{db}}.STG.V_EMPLOYEES_CURRENT
),
CURRENT_JOB as (
    select *
    from {{db}}.INT.V_EMPLOYEE_JOB_HISTORY
    where IS_CURRENT_JOB = true
),
CURRENT_COMP as (
    select *
    from {{db}}.INT.V_EMPLOYEE_COMP_HISTORY
    where IS_CURRENT_COMP = true
)
select
    e.EMPLOYEE_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.FIRST_NAME || ' ' || e.LAST_NAME as EMPLOYEE_NAME,
    e.GENDER,
    e.ETHNICITY,
    e.DATE_OF_BIRTH,
    e.HIRE_DATE,
    e.TERMINATION_DATE,
    e.EMPLOYMENT_STATUS,
    e.EMPLOYMENT_TYPE,
    e.IS_ACTIVE,
    e.EMAIL,
    j.JOB_ID as CURRENT_JOB_ID,
    j.JOB_TITLE as CURRENT_JOB_TITLE,
    j.JOB_FAMILY as CURRENT_JOB_FAMILY,
    j.JOB_LEVEL as CURRENT_JOB_LEVEL,
    j.GRADE_BAND as CURRENT_GRADE_BAND,
    j.DEPARTMENT_ID as CURRENT_DEPARTMENT_ID,
    j.DEPARTMENT_NAME as CURRENT_DEPARTMENT_NAME,
    j.BUSINESS_UNIT as CURRENT_BUSINESS_UNIT,
    j.COST_CENTER as CURRENT_COST_CENTER,
    j.MANAGER_EMPLOYEE_ID as CURRENT_MANAGER_EMPLOYEE_ID,
    j.MANAGER_NAME as CURRENT_MANAGER_NAME,
    j.LOCATION_CODE as CURRENT_LOCATION_CODE,
    j.VALID_FROM as CURRENT_JOB_START_DATE,
    c.SALARY_AMOUNT as CURRENT_SALARY_AMOUNT,
    c.BONUS_TARGET_PCT as CURRENT_BONUS_TARGET_PCT,
    c.CURRENCY_CODE as CURRENT_CURRENCY_CODE,
    c.CHANGE_REASON as CURRENT_SALARY_CHANGE_REASON,
    c.VALID_FROM as CURRENT_SALARY_EFFECTIVE_DATE
from CURRENT_EMP e
left join CURRENT_JOB j
    on e.EMPLOYEE_ID = j.EMPLOYEE_ID
left join CURRENT_COMP c
    on e.EMPLOYEE_ID = c.EMPLOYEE_ID;
