DEFINE VIEW {{db}}.INT.V_CURRENCY_RATES_WITH_INVERSE(
    RATE_DATE,
    FROM_CURRENCY,
    TO_CURRENCY,
    RATE,
    INVERSE_RATE,
    SOURCE_SYSTEM
) as
select
    RATE_DATE,
    BASE_CURRENCY as FROM_CURRENCY,
    TARGET_CURRENCY as TO_CURRENCY,
    EXCHANGE_RATE as RATE,
    round(1.0 / nullif(EXCHANGE_RATE, 0), 8) as INVERSE_RATE,
    SOURCE_SYSTEM
from {{db}}.STG.V_CURRENCY_RATES_LATEST
union all
select
    RATE_DATE,
    TARGET_CURRENCY as FROM_CURRENCY,
    BASE_CURRENCY as TO_CURRENCY,
    round(1.0 / nullif(EXCHANGE_RATE, 0), 8) as RATE,
    EXCHANGE_RATE as INVERSE_RATE,
    SOURCE_SYSTEM
from {{db}}.STG.V_CURRENCY_RATES_LATEST
where BASE_CURRENCY <> TARGET_CURRENCY;
