-- Ownership grants: ensure each schema's objects are owned by the corresponding RWC database role.

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA {{db}}.RPT
    TO DATABASE ROLE {{db}}.RPT_RWC;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA {{db}}.STG
    TO DATABASE ROLE {{db}}.STG_RWC;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA {{db}}.INT
    TO DATABASE ROLE {{db}}.INT_RWC;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA {{db}}.RAW
    TO DATABASE ROLE {{db}}.RAW_RWC;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA {{db}}.DM
    TO DATABASE ROLE {{db}}.DM_RWC;
