DEFINE VIEW {{db}}.INT.V_BUDGET_WITH_VARIANCE(
    BUDGET_ID,
    FISCAL_YEAR,
    FISCAL_QUARTER,
    COST_CENTER_ID,
    COST_CENTER_NAME,
    DIVISION,
    ACCOUNT_ID,
    ACCOUNT_NAME,
    ACCOUNT_TYPE,
    BUDGET_AMOUNT,
    ACTUAL_AMOUNT,
    VARIANCE_AMOUNT,
    VARIANCE_PCT,
    CURRENCY_CODE,
    BUDGET_VERSION
) as
select
    b.BUDGET_ID,
    b.FISCAL_YEAR,
    b.FISCAL_QUARTER,
    b.COST_CENTER_ID,
    cc.COST_CENTER_NAME,
    cc.DIVISION,
    b.ACCOUNT_ID,
    gl.ACCOUNT_NAME,
    gl.ACCOUNT_TYPE,
    b.BUDGET_AMOUNT,
    b.ACTUAL_AMOUNT,
    b.ACTUAL_AMOUNT - b.BUDGET_AMOUNT as VARIANCE_AMOUNT,
    case when b.BUDGET_AMOUNT <> 0
        then round((b.ACTUAL_AMOUNT - b.BUDGET_AMOUNT) / b.BUDGET_AMOUNT * 100, 2)
        else null
    end as VARIANCE_PCT,
    b.CURRENCY_CODE,
    b.BUDGET_VERSION
from {{db}}.STG.V_BUDGET_ITEMS b
left join {{db}}.STG.V_COST_CENTERS cc on b.COST_CENTER_ID = cc.COST_CENTER_ID
left join {{db}}.STG.V_GL_ACCOUNTS gl on b.ACCOUNT_ID = gl.ACCOUNT_ID;
