DEFINE TABLE {{db}}.RAW.CURRENCY_RATES_RAW (
    RAW_SK NUMBER(38,0) autoincrement start 1 increment 1 noorder,
    RAW_ROW_ID VARCHAR(16777216),
    RATE_DATE DATE,
    BASE_CURRENCY VARCHAR(3),
    TARGET_CURRENCY VARCHAR(3),
    EXCHANGE_RATE NUMBER(18,8),
    SOURCE_SYSTEM VARCHAR(16777216),
    SRC_UPDATED_AT TIMESTAMP_NTZ(9),
    LOAD_TS TIMESTAMP_NTZ(9)
);
