DEFINE DYNAMIC TABLE {{db}}.DM.D_EMPLOYEE_CURRENT
    lag = '5 minutes'
    refresh_mode = 'AUTO'
    initialize = 'ON_CREATE'
    warehouse = {{transform_wh}}
as
select
    row_number() over (order by e.EMPLOYEE_ID) as EMPLOYEE_KEY,
    d.DEPARTMENT_KEY,
    j.JOB_KEY,
    e.EMPLOYEE_ID,
    e.EMPLOYEE_NAME,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.GENDER,
    e.ETHNICITY,
    e.DATE_OF_BIRTH,
    e.HIRE_DATE,
    e.TERMINATION_DATE,
    e.EMPLOYMENT_STATUS,
    e.EMPLOYMENT_TYPE,
    e.IS_ACTIVE,
    e.EMAIL,
    e.CURRENT_JOB_ID,
    e.CURRENT_JOB_TITLE,
    e.CURRENT_JOB_FAMILY,
    e.CURRENT_JOB_LEVEL,
    e.CURRENT_GRADE_BAND,
    e.CURRENT_DEPARTMENT_ID,
    e.CURRENT_DEPARTMENT_NAME,
    e.CURRENT_BUSINESS_UNIT,
    e.CURRENT_COST_CENTER,
    e.CURRENT_MANAGER_EMPLOYEE_ID,
    e.CURRENT_MANAGER_NAME,
    e.CURRENT_LOCATION_CODE,
    e.CURRENT_JOB_START_DATE,
    e.CURRENT_SALARY_AMOUNT,
    e.CURRENT_BONUS_TARGET_PCT,
    e.CURRENT_CURRENCY_CODE,
    e.CURRENT_SALARY_CHANGE_REASON,
    e.CURRENT_SALARY_EFFECTIVE_DATE,
    datediff('year', e.HIRE_DATE, current_date()) as YEARS_OF_SERVICE
from {{db}}.INT.V_EMPLOYEE_CURRENT_SNAPSHOT e
left join {{db}}.DM.D_DEPARTMENT_CURRENT d
    on e.CURRENT_DEPARTMENT_ID = d.DEPARTMENT_ID
left join {{db}}.DM.D_JOB_CURRENT j
    on e.CURRENT_JOB_ID = j.JOB_ID;
